export enum UserRole {
  CLIENT = 'CLIENT',
  PROVIDER = 'PROVIDER',
  ADMIN = 'ADMIN',
  SUPER_ADMIN = 'SUPER_ADMIN',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  PENDING_EMAIL_VERIFICATION = 'PENDING_EMAIL_VERIFICATION',
  SUSPENDED = 'SUSPENDED',
  BANNED = 'BANNED',
}

export enum ProviderLevel {
  LEVEL_0_NEW = 'LEVEL_0_NEW',
  LEVEL_1_VERIFIED = 'LEVEL_1_VERIFIED',
  LEVEL_2_TRUSTED = 'LEVEL_2_TRUSTED',
  LEVEL_3_GOLD = 'LEVEL_3_GOLD',
  LEVEL_4_PLATINUM = 'LEVEL_4_PLATINUM',
  LEVEL_5_DIAMOND = 'LEVEL_5_DIAMOND',
}

export * from './reputation';
export * from './task-types';

export enum ProviderVerificationStatus {
  NOT_STARTED = 'NOT_STARTED',
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  NEEDS_CORRECTION = 'NEEDS_CORRECTION',
}

export enum VerificationStatus {
  NOT_STARTED = 'NOT_STARTED',
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  NEEDS_CORRECTION = 'NEEDS_CORRECTION',
}

export enum CertificationStatus {
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum TaskStatus {
  DRAFT = 'DRAFT',
  PUBLISHED = 'PUBLISHED',
  RECEIVING_OFFERS = 'RECEIVING_OFFERS',
  OFFER_ACCEPTED = 'OFFER_ACCEPTED',
  PROTECTED_PAYMENT_CONFIRMED = 'PROTECTED_PAYMENT_CONFIRMED',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  DISPUTED = 'DISPUTED',
}

export enum OfferStatus {
  SENT = 'SENT',
  VIEWED = 'VIEWED',
  PENDING = 'PENDING',
  ACCEPTED = 'ACCEPTED',
  REJECTED = 'REJECTED',
  COUNTERED = 'COUNTERED',
  EXPIRED = 'EXPIRED',
  WITHDRAWN = 'WITHDRAWN',
}

export enum BookingStatus {
  CONFIRMED = 'CONFIRMED',
  PENDING_PAYMENT = 'PENDING_PAYMENT',
  PAID = 'PAID',
  IN_PROGRESS = 'IN_PROGRESS',
  COMPLETED_BY_PROVIDER = 'COMPLETED_BY_PROVIDER',
  CONFIRMED_BY_CLIENT = 'CONFIRMED_BY_CLIENT',
  COMPLETED = 'COMPLETED',
  CANCELLED = 'CANCELLED',
  DISPUTED = 'DISPUTED',
}

export enum ProtectedPaymentStatus {
  NOT_STARTED = 'NOT_STARTED',
  PENDING = 'PENDING',
  PROTECTED = 'PROTECTED',
  APPROVED_FOR_PAYOUT = 'APPROVED_FOR_PAYOUT',
  DISPUTED = 'DISPUTED',
  REFUNDED = 'REFUNDED',
}

export enum PricingType {
  FIXED = 'FIXED',
  HOURLY = 'HOURLY',
  DAILY = 'DAILY',
  TECHNICAL_VISIT = 'TECHNICAL_VISIT',
  OPEN_TO_OFFERS = 'OPEN_TO_OFFERS',
}

export enum PaymentStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
  REFUNDED = 'REFUNDED',
}

export enum PayoutStatus {
  PENDING = 'PENDING',
  PROCESSING = 'PROCESSING',
  COMPLETED = 'COMPLETED',
  FAILED = 'FAILED',
}

export enum DisputeStatus {
  OPEN = 'OPEN',
  UNDER_REVIEW = 'UNDER_REVIEW',
  RESOLVED = 'RESOLVED',
  CLOSED = 'CLOSED',
}

export enum LedgerEntryType {
  CREDIT = 'CREDIT',
  DEBIT = 'DEBIT',
  HOLD = 'HOLD',
  RELEASE = 'RELEASE',
}

export enum ModerationEntityType {
  TASK = 'TASK',
  OFFER = 'OFFER',
  REVIEW = 'REVIEW',
  CHAT_MESSAGE = 'CHAT_MESSAGE',
  PROVIDER_PROFILE = 'PROVIDER_PROFILE',
}

export enum ModerationStatus {
  OPEN = 'OPEN',
  REVIEWED = 'REVIEWED',
  ACTIONED = 'ACTIONED',
  DISMISSED = 'DISMISSED',
}

export enum MediaPurpose {
  AVATAR = 'AVATAR',
  PROVIDER_PORTFOLIO = 'PROVIDER_PORTFOLIO',
  VERIFICATION_DOCUMENT = 'VERIFICATION_DOCUMENT',
  VERIFICATION_SELFIE = 'VERIFICATION_SELFIE',
  TASK_PHOTO = 'TASK_PHOTO',
  TASK_VIDEO = 'TASK_VIDEO',
  BOOKING_EVIDENCE = 'BOOKING_EVIDENCE',
  DISPUTE_EVIDENCE = 'DISPUTE_EVIDENCE',
}

export enum MediaStatus {
  UPLOADED = 'UPLOADED',
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  DELETED = 'DELETED',
}

export enum LocationVisibility {
  PRIVATE = 'PRIVATE',
  APPROXIMATE = 'APPROXIMATE',
  BOOKING_ONLY = 'BOOKING_ONLY',
}

export enum NotificationType {
  TASK_UPDATE = 'TASK_UPDATE',
  OFFER_RECEIVED = 'OFFER_RECEIVED',
  BOOKING_UPDATE = 'BOOKING_UPDATE',
  PAYMENT_UPDATE = 'PAYMENT_UPDATE',
  PAYOUT_UPDATE = 'PAYOUT_UPDATE',
  DISPUTE_UPDATE = 'DISPUTE_UPDATE',
  CHAT_MESSAGE = 'CHAT_MESSAGE',
  SYSTEM = 'SYSTEM',
}
